import { getDb } from "../api/queries/connection";
import { cars, routes } from "./schema";

async function seed() {
  const db = getDb();

  // Seed cars with original EasyOutstation pricing
  const carData = [
    {
      name: "Swift Dzire",
      brand: "Maruti Suzuki",
      model: "Dzire",
      category: "sedan" as const,
      seats: 4,
      pricePerKm: "12.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "diesel" as const,
      transmission: "manual" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags"]),
      imageUrl: "/cars/swift-dzire.jpg",
      galleryImages: JSON.stringify(["/cars/swift-dzire.jpg"]),
      rating: "4.50",
      reviewCount: 128,
      isAvailable: true,
      isPopular: true,
      description: "Budget-friendly sedan ideal for couples and small families. Comfortable seating, smooth performance on highways, and excellent fuel efficiency.",
    },
    {
      name: "Toyota Etios",
      brand: "Toyota",
      model: "Etios",
      category: "sedan" as const,
      seats: 4,
      pricePerKm: "13.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "diesel" as const,
      transmission: "manual" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS"]),
      imageUrl: "/cars/toyota-etios.jpg",
      galleryImages: JSON.stringify(["/cars/toyota-etios.jpg"]),
      rating: "4.60",
      reviewCount: 96,
      isAvailable: true,
      isPopular: false,
      description: "Reliable and spacious sedan with Toyota's legendary durability. Perfect for long-distance travel with superior comfort.",
    },
    {
      name: "Mahindra Xylo",
      brand: "Mahindra",
      model: "Xylo",
      category: "suv" as const,
      seats: 6,
      pricePerKm: "16.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "diesel" as const,
      transmission: "manual" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS", "Roof Rails"]),
      imageUrl: "/cars/mahindra-xylo.jpg",
      galleryImages: JSON.stringify(["/cars/mahindra-xylo.jpg"]),
      rating: "4.40",
      reviewCount: 74,
      isAvailable: true,
      isPopular: false,
      description: "Rugged and powerful SUV with ample space for 6 passengers. Ideal for hilly terrain and adventure trips.",
    },
    {
      name: "Maruti Ertiga",
      brand: "Maruti Suzuki",
      model: "Ertiga",
      category: "muv" as const,
      seats: 6,
      pricePerKm: "15.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "petrol" as const,
      transmission: "manual" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS", "Third Row Seating"]),
      imageUrl: "/cars/maruti-ertiga.jpg",
      galleryImages: JSON.stringify(["/cars/maruti-ertiga.jpg"]),
      rating: "4.70",
      reviewCount: 215,
      isAvailable: true,
      isPopular: true,
      description: "Spacious MUV perfect for family trips. Comfortable seating, ample legroom, and sufficient luggage space for long journeys.",
    },
    {
      name: "Toyota Innova",
      brand: "Toyota",
      model: "Innova",
      category: "muv" as const,
      seats: 6,
      pricePerKm: "19.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "diesel" as const,
      transmission: "manual" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS", "Third Row Seating", "Leather Seats"]),
      imageUrl: "/cars/toyota-innova.jpg",
      galleryImages: JSON.stringify(["/cars/toyota-innova.jpg"]),
      rating: "4.80",
      reviewCount: 342,
      isAvailable: true,
      isPopular: true,
      description: "The iconic Indian family vehicle. Known for reliability, comfort, and performance on both highways and hills.",
    },
    {
      name: "Toyota Innova Crysta",
      brand: "Toyota",
      model: "Innova Crysta",
      category: "premium" as const,
      seats: 6,
      pricePerKm: "20.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "diesel" as const,
      transmission: "automatic" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS", "Third Row Seating", "Leather Seats", "Sunroof", "Cruise Control"]),
      imageUrl: "/cars/toyota-innova-crysta.jpg",
      galleryImages: JSON.stringify(["/cars/toyota-innova-crysta.jpg"]),
      rating: "4.90",
      reviewCount: 456,
      isAvailable: true,
      isPopular: true,
      description: "Premium MPV with powerful engine, superior suspension, and luxurious interiors. The top choice for hill station travel.",
    },
    {
      name: "Kia Carens",
      brand: "Kia",
      model: "Carens",
      category: "premium" as const,
      seats: 6,
      pricePerKm: "17.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "petrol" as const,
      transmission: "automatic" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS", "Third Row Seating", "Panoramic Sunroof", "Wireless Charging"]),
      imageUrl: "/cars/kia-carens.jpg",
      galleryImages: JSON.stringify(["/cars/kia-carens.jpg"]),
      rating: "4.75",
      reviewCount: 89,
      isAvailable: true,
      isPopular: false,
      description: "Modern premium MPV with advanced features, excellent comfort, and contemporary design for the discerning traveler.",
    },
    {
      name: "Toyota Innova Hycross",
      brand: "Toyota",
      model: "Innova Hycross",
      category: "luxury" as const,
      seats: 6,
      pricePerKm: "22.00",
      driverCharges: "400.00",
      minKmPerDay: 250,
      fuelType: "hybrid" as const,
      transmission: "automatic" as const,
      features: JSON.stringify(["AC", "Music System", "Ice Box", "Medical Kit", "GPS Navigation", "Power Steering", "Airbags", "ABS", "Third Row Seating", "Leather Seats", "Panoramic Sunroof", "ADAS", "Wireless Charging", "Ambient Lighting"]),
      imageUrl: "/cars/toyota-innova-hycross.jpg",
      galleryImages: JSON.stringify(["/cars/toyota-innova-hycross.jpg"]),
      rating: "4.95",
      reviewCount: 67,
      isAvailable: true,
      isPopular: true,
      description: "Flagship luxury hybrid MPV with refined interiors, cutting-edge technology, and exceptional ride quality for maximum comfort.",
    },
  ];

  // Seed routes
  const routeData = [
    {
      fromCity: "Delhi",
      toCity: "Manali",
      distanceKm: 540,
      durationHours: 12,
      basePrice: "6480.00",
      imageUrl: "/hero-bg.jpg",
      isPopular: true,
      description: "Scenic mountain journey via Chandigarh, Bilaspur, and Kullu. Perfect for hill station vacations.",
    },
    {
      fromCity: "Delhi",
      toCity: "Jaipur",
      distanceKm: 280,
      durationHours: 5,
      basePrice: "3360.00",
      imageUrl: "/cars/toyota-innova.jpg",
      isPopular: true,
      description: "The Golden Triangle route to the Pink City. Rich cultural heritage and royal architecture await.",
    },
    {
      fromCity: "Delhi",
      toCity: "Agra",
      distanceKm: 230,
      durationHours: 4,
      basePrice: "2760.00",
      imageUrl: "/cars/swift-dzire.jpg",
      isPopular: true,
      description: "Visit the Taj Mahal and Agra Fort. A must-do heritage trip from Delhi.",
    },
    {
      fromCity: "Delhi",
      toCity: "Rishikesh",
      distanceKm: 240,
      durationHours: 5,
      basePrice: "2880.00",
      imageUrl: "/cars/maruti-ertiga.jpg",
      isPopular: true,
      description: "Yoga capital of the world. Spiritual retreat and adventure sports destination.",
    },
    {
      fromCity: "Delhi",
      toCity: "Chandigarh",
      distanceKm: 250,
      durationHours: 4,
      basePrice: "3000.00",
      imageUrl: "/cars/toyota-etios.jpg",
      isPopular: false,
      description: "The City Beautiful. Gateway to Himachal and Punjab.",
    },
    {
      fromCity: "Delhi",
      toCity: "Dehradun",
      distanceKm: 250,
      durationHours: 5,
      basePrice: "3000.00",
      imageUrl: "/cars/mahindra-xylo.jpg",
      isPopular: false,
      description: "Capital of Uttarakhand. Gateway to Mussoorie and hill stations.",
    },
  ];

  try {
    await db.insert(cars).values(carData);
    console.log("Cars seeded successfully");
  } catch (e) {
    console.log("Cars may already exist", e);
  }

  try {
    await db.insert(routes).values(routeData);
    console.log("Routes seeded successfully");
  } catch (e) {
    console.log("Routes may already exist", e);
  }
}

seed().catch(console.error);
